name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2

    - name: Setup Visual Studio Build Tools
      uses: ilammy/msvc-dev-cmd@v1
      with:
        toolset: '14.3'
        
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore NuGet packages
      run: nuget restore WeatherForcast.sln

    - name: Install Google Test
      run: nuget install Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn -Version 1.8.1.7

    - name: Download MySQL Connector
      run: |
        curl -L -o mysql.zip https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-8.0.25-winx64.zip
    
    - name: Extract MySQL Connector
      run: |
        Expand-Archive -Path mysql.zip -DestinationPath ${{github.workspace}}/mysql-connector

    - name: Set Environment Variables
      run: |
        echo "MYSQL_HOME=${{github.workspace}}/mysql-connector" >> $GITHUB_ENV
        echo "PATH=${{github.workspace}}/mysql-connector/bin;$PATH" >> $GITHUB_ENV

    - name: List Directory Contents
      run: |
        ls "${{github.workspace}}/mysql-connector"
        ls "${{github.workspace}}/mysql-connector/mysql-8.0.25-winx64/include"

    - name: Set up Visual Studio and SDK paths
      run: |
        $vsPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
        $sdkPath = "C:\Program Files (x86)\Windows Kits\10"
        $vcToolsPath = Join-Path $vsPath "VC\Tools\MSVC"
        $latestVcTools = Get-ChildItem $vcToolsPath | Sort-Object Name -Descending | Select-Object -First 1
        $vcIncludePath = Join-Path $latestVcTools.FullName "include"
        $vcLibPath = Join-Path $latestVcTools.FullName "lib\x64"
    
        $sdkIncludePath = Join-Path $sdkPath "Include\10.0.19041.0"
        $sdkLibPath = Join-Path $sdkPath "Lib\10.0.19041.0\ucrt\x64"
        $sdkUMPath = Join-Path $sdkPath "Lib\10.0.19041.0\um\x64"
    
        $sqlInclude = "${{github.workspace}}/mysql-connector/mysql-8.0.25-winx64/include"
        $sqlLib = "${{github.workspace}}/mysql-connector/mysql-8.0.25-winx64/lib"
    
        "INCLUDE_PATH=$vcIncludePath;$sdkIncludePath\ucrt;$sdkIncludePath\um;$sdkIncludePath\shared;$sqlInclude" | Out-File -FilePath $env:GITHUB_ENV -Append
        "LIBRARY_PATH=$vcLibPath;$sdkLibPath;$sdkUMPath;$sqlLib" | Out-File -FilePath $env:GITHUB_ENV -Append
      shell: pwsh
    
    - name: Output configured paths
      run: |
        echo "Include path: ${{ env.INCLUDE_PATH }}"
        echo "Library path: ${{ env.LIBRARY_PATH }}"
      shell: pwsh


    - name: Build with MSBuild
      run: |
        msbuild WeatherForcast.sln /p:Configuration=Release /p:Platform="x64" /p:IncludePath="${{ env.IncludePath }}" /p:LibraryPath="${{ env.LibraryPath }}" /p:AdditionalDependencies="libmysql.lib"
      shell: pwsh

    - name: Run Tests
      working-directory: ./x64/Release/
      run: |
        WeatherForcastGoogleTest.exe
        echo "Tests completed!"
      shell: pwsh
