name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up MSBuild path
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore NuGet packages
      run: nuget restore WeatherForcast.sln

    - name: Install Google Test
      run: nuget install Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn -Version 1.8.1.7

    - name: Build with MSBuild
      run: msbuild WeatherForcast.sln /p:Configuration=Release

    - name: Run tests
      run: |
        .\Debug\WeatherForcastGoogleTest.exe
        echo "Tests completed!"
