name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore NuGet packages
      run: nuget restore WeatherForcast.sln

    - name: Install Google Test
      run: nuget install Microsoft.googletest.v140.windesktop.msvcstl.static.rt-dyn -Version 1.8.1.7

    - name: Download MySQL Connector
      run: |
        curl -L -o mysql.zip https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-8.0.25-winx64.zip
    
    - name: Extract MySQL Connector
      run: |
        Expand-Archive -Path mysql.zip -DestinationPath ${{github.workspace}}/mysql-connector

    - name: Set Environment Variables
      run: |
        echo "MYSQL_HOME=${{github.workspace}}/mysql-connector" >> $GITHUB_ENV
        echo "PATH=${{github.workspace}}/mysql-connector/bin;$PATH" >> $GITHUB_ENV

    - name: List Directory Contents
      run: |
        ls "${{github.workspace}}/mysql-connector"
        ls "${{github.workspace}}/mysql-connector/mysql-8.0.25-winx64/include"

    - name: Set up MySQL paths
      run: |
        echo "IncludePath=D:\a\WeatherForcast\WeatherForcast\mysql-connector\mysql-8.0.25-winx64\include;$(VC_IncludePath);$(WindowsSDK_IncludePath)" >> $GITHUB_ENV
        echo "LibraryPath=D:\a\WeatherForcast\WeatherForcast\mysql-connector\mysql-8.0.25-winx64\lib;$(VC_LibraryPath_x64);$(WindowsSDK_LibraryPath_x64)" >> $GITHUB_ENV

    - name: Build with MSBuild
      run: |
        msbuild WeatherForcast.sln /p:Configuration=Release /p:Platform="x64" /p:IncludePath="${{ env.IncludePath }}" /p:LibraryPath="${{ env.LibraryPath }}" /p:AdditionalDependencies="libmysql.lib"
      shell: pwsh

    - name: Run Tests
      working-directory: ./x64/Release/
      run: |
        WeatherForcastGoogleTest.exe
        echo "Tests completed!"
      shell: pwsh
